### ISSUE TITLE
How to generate my own database

### ISSUE THREAD

**Issue by thegodone** [mrodobbe/Rxn-INSIGHT#2]
You provide the uspto parquet but I would like to generate my own database. Do you have a script to apply to another database ?

**Comment by mrodobbe** [comment]
Dear Guillaume,

Thank you for your question. A new module is added to easily generate a database that is compatible with the suggest_conditions function.

```
from rxn_insight.database import Database
from rxn_insight.reaction import Reaction

db = Database()
db.create_database_from_csv(fname="test.csv", reaction_column="RXN", solvent_column="SOLVENTS")
r = Reaction("CCO>>CC=O")
sug_conds = r.suggest_conditions(db.df)
```

If you create your database from a csv, you need to provide the column names that you have used in your csv file.
Two arguments are required: `fname` (location of your csv file) and `reaction_column` (the name of the column containing the reactions). 
The optional arguments are `solvent_column`, `reagent_column`, `catalyst_column`, `yield_column`, and `ref_column`. Default (or when these columns are not available), the column names will be set to respectively SOLVENT, REAGENT, CATALYST, YIELD, REF.

I hope this helps.

Maarten

**Comment by thegodone** [comment]
perfect thanks for this additional method.
